package postgres;


import FileParser.ParseFile;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sakshi
 */
public class confde extends javax.swing.JFrame {

  
    public confde() {
        initComponents();
         jLabel9.setForeground(Color.RED);
         jLabel9.setFont(new Font("italic", Font.BOLD, 40));
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
         jLabel8.setVisible(false);
    }
    
    private int checkdigit(String ardc)
    {
         int c=0;
        int arr[];
        arr=new int[ardc.length()];
        
     
    int s=0;
        
   for(int i=0;i<ardc.length();i++)
   {
       char ch=ardc.charAt(i);
       int ardc1=Integer.parseInt(ch+"");
       
            arr[i]=ardc1;
            if(i%2!=0)
            {
                arr[i]=arr[i]*2;
            }
            s=0;
            if(arr[i]>9)
            {
                int g=arr[i];
                
                while(g!=0)
                {
                    int r1=g%10;
                    s=s+r1;
                    g=g/10;
                         System.out.println(arr[i]);
                }
                g=s;
                arr[i]=g;
             }
            
            
        
   }
 
        int st=0,cd=0;
        for(int i=0;i<ardc.length();i++)
            st=st+arr[i];
        System.out.println("the sum is "+st);
        
        if(st%10==0)
            cd=0;
        else
        cd=10-(st%10);
        System.out.println("check digit= "+cd);
        String ss =  String.valueOf(cd);
        System.out.println("cd= "+ss);
        return cd;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Acquirer Institution ID Code");

        jLabel2.setText("Acquirer Reference Data");

        jLabel3.setText("Transaction Originator ID Code");

        jLabel4.setText("Card Acceptor Terminal ID");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("CONFIGURABLE DATA ELEMENTS AT C.S");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jTextField3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
 Date date1 = new Date() ;
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd") ;
        String dated=dateFormat1.format(date1);
        String date[]=dated.split("-");
        int sum=0;
        int months[]={0,31,28,31,30,31,30,31,31,30,31,30,31};
         if(Integer.parseInt(date[0])%4==0)
                months[2]=29;
           
        for(int i=1;i<Integer.parseInt(date[1]);i++)
        {
             sum=sum+months[i];
            
        }
        sum=sum+Integer.parseInt(date[2]);
        String JulianDate=date[0].charAt(date[0].length()-1)+""+sum;
        System.out.println("julian date is "+JulianDate);
             HashMap<String, String> HM1=new HashMap<String,String>();
              
               HM1=ParseFile.GetVal("conf_d.conf", "ard");
               
               
                String aid=HM1.get("ard.aid");
                String rrn=HM1.get("ard.rrn");
                String d_ard=aid+JulianDate+rrn;
    
            
                               String d_acqinstcd=jTextField1.getText();
   String d_txnorginstcd=jTextField3.getText();
   String d_crdacpttrmid=jTextField4.getText();
  int cd=checkdigit(d_ard);
    System.out.println("check digit= "+cd);
    String ard=d_ard+(cd+"");
    d_ard=ard;
    System.out.println("ard= "+ard);
    jLabel6.setVisible(true);
    jLabel6.setText(d_ard);
    if(!(d_acqinstcd.length()<=11)) {
   // jTextField1.setText(jTextField1.getText().substring(0, 1));
   jLabel5.setVisible(true);
   jLabel5.setText("incorrect format");
   return;
    }  
    if(!(d_ard.length()<=23)) {
   // jTextField1.setText(jTextField1.getText().substring(0, 1));
   jLabel6.setVisible(true);
   jLabel6.setText("incorrect format");
   return;
    }
    if(!(d_txnorginstcd.length()==11)) {
   // jTextField1.setText(jTextField1.getText().substring(0, 1));
   jLabel7.setVisible(true);
   jLabel7.setText("incorrect format");
   return;
    }
    if(!(d_crdacpttrmid.length()==16)) {
   // jTextField1.setText(jTextField1.getText().substring(0, 1));
   jLabel8.setVisible(true);
   jLabel8.setText("incorrect format");
   return;
    }
    
    Connection con=null;
        Statement stmt=null;
        int id=1;
        
        try
        {
            HashMap<String, String> HM=new HashMap<String,String>();
            
               HM=ParseFile.GetVal("conf_d.conf", "Con");
               
               String db=HM.get("Con.database");
                String uname=HM.get("Con.username");
                String pswd=HM.get("Con.password");
                String port=HM.get("Con.port");
                String Driver=HM.get("Con.driver");
                String str=HM.get("Con.con_string");
                String Host=HM.get("Con.host");
               
                Class.forName(Driver);
                String st=str+"//"+Host+port+"/"+db;
            
            con = DriverManager.getConnection(st,
               uname, pswd);
            
            con.setAutoCommit(true);
            System.out.println("Database Connected.");
            String query="update configurable_tb SET  acqinstcd='"+d_acqinstcd+"', ard='"+d_ard+"', txnorginstcd='"+d_txnorginstcd+"' where crdacpttrmid= '"+d_crdacpttrmid+"'";
             System.out.println(query);
             stmt = con.createStatement();
        stmt.executeUpdate(query);
        id++;
        JOptionPane.showMessageDialog(this, "Saved");
        }
        catch (ClassNotFoundException | SQLException e) 
        {
            
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            //System.exit(0);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confde().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}


