/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;
import FileParser.ParseFile;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.ComboBoxModel;
import java.lang.String;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JFrame;
/**
 *
 * @author cdac
 */
public class report extends javax.swing.JFrame {
int index=0;
    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        JFrame jfrm=new JFrame();
    //    jfrm.setSize(200,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 200, 500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("From Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 160, 73, 14);

        jLabel2.setText("To Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 160, 66, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "datewise", "monthwise" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 50, 190, 20);

        jLabel3.setText("Choose the year and month");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 160, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(340, 120, 90, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(200, 120, 100, 20);

        jLabel4.setText("Choose the type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 50, 90, 14);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 240, 65, 23);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(340, 160, 91, 20);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(160, 160, 91, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
         jLabel3.setVisible(false);
          jComboBox2.setVisible(false);
          jComboBox3.setVisible(false);
          jLabel1.setVisible(false);
          jLabel2.setVisible(false);
          jDateChooser1.setVisible(false);
          jDateChooser2.setVisible(false);
//        jComboBox2.addItem("Jan");
//        jComboBox2.addItem("Feb");
//        jComboBox2.addItem("Mar");
//        jComboBox2.addItem("Apr");
//        jComboBox2.addItem("May");
//        jComboBox2.addItem("Jun");
//        jComboBox2.addItem("Jul");
//        jComboBox2.addItem("Aug");
//        jComboBox2.addItem("Sep");
//        jComboBox2.addItem("Oct");
//        jComboBox2.addItem("Nov");
//        jComboBox2.addItem("Dec");
//        jComboBox3.addItem("2016");
//        jComboBox3.addItem("2017");
//        jComboBox3.addItem("2018");
//        jComboBox3.addItem("2019");
//        jComboBox3.addItem("2020");
//        jComboBox3.addItem("2021");
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt;
        long sum=0;
        String months[]={"","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};
       // String months1[]={"","01","02","03","04","05","06","07","08","09","10","11","12"};
        try {

            HashMap<String, String> HM=new HashMap<String,String>();
            
               HM=ParseFile.GetVal("conf_d.conf", "Con");
               
               String db=HM.get("Con.database");
                String uname=HM.get("Con.username");
                String pswd=HM.get("Con.password");
                String port=HM.get("Con.port");
                String Driver=HM.get("Con.driver");
                String str=HM.get("Con.con_string");
                String Host=HM.get("Con.host");
                
                Class.forName(Driver);
                String st=str+"//"+Host+port+"/"+db;
            
            con = DriverManager.getConnection(st,
               uname, pswd);
            //  con.setAutoCommit(true);
            System.out.println("Database Connected.");
            stmt = con.createStatement();
            //   System.out.println("enter the name of the table");
            // tbname=s.next();
            String sql2 ="CREATE TABLE IF NOT EXISTS Dynamic_tb "+"(DtTmLcTxn  TIMESTAMP ,"+
            "   PAN BIGINT , " +
            "PSN BIGINT ," +
            "   Movtyp INT ,"+
            "   TxnTypq INT ,"+
            "   AmtAdd INT ,"+
            "   crdacpttrmid TEXT ," +
            "   AmtTxn TEXT ,\n"+
            "   modified INT);";
            stmt.executeUpdate(sql2);
            /*    String sql3="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES ('2016/06/21 11:33:08', 214, 23541, 2344443, 235436556, 23455455,4546571,3543545,2354556 )";
            String sql4="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES('2016/06/22 11:33:09', 234, 23543, 2344444, 235436566, 23455454,4546574,6543753,2354555 )";
            String sql5="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES ('2016/06/23 11:33:10', 224, 23542, 2344445, 235436576, 23455453,4546577,4356271,2354554 )";
            String sql6="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES ('2016/06/24 11:33:11', 244, 23545, 2344446, 235436586, 23455452,4546576,5435435,2354553 )";
            String sql7="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES ('2016/06/25 11:33:12', 254, 23549, 2344447, 235436946, 23455451,4546578,3543444,2354552 )";
            String sql8="INSERT INTO Dynamic_tb (DtTmLcTxn,PAN,PSN,Movtyp,TxnTypq,AmtAdd,crdacpttrmid,AmtTxn,modified) VALUES ('2016/06/26 11:33:13', 274, 23548, 2344448, 235436546, 23455456,4546579,7623645,2354551 )";
            */
            //  String sql11 ="Delete from Dynamic_tb";
            if(index==1)
            {
                String datetime_month[]=new String[2];
                String month=jComboBox1.getName();
                int index1=jComboBox2.getSelectedIndex();
                index1=index1+1;
                String sql10="select AmtTxn from Dynamic_tb where EXTRACT(MONTH from dttmlctxn)= '"+index1+"'";
                   ResultSet rs1=stmt.executeQuery(sql10);
            while(rs1.next())
            {
                long amount=Long.parseLong(rs1.getString(1));
                sum=sum+amount;
            }
            System.out.println("sum is"+sum);
            JOptionPane.showMessageDialog(this, "Amount"+ " "+sum);

            //String sql10="Select AmtTxn from Dynamic_tb where DtTmLcTxn=";
           
            }
            else if(index==0)
            {
            String datetime_from[]=new String[2];
            String datetime_to[]=new String[2];
          String dateFromDateChooser = jDateChooser1.getDate().toString();
           String dateToDateChooser = jDateChooser2.getDate().toString();
            datetime_from=dateFromDateChooser.split(" ");
            datetime_to=dateToDateChooser.split(" ");
            String datetm_from="",datetm_to="";

            for(int i=1;i<=12;i++)
            {
                if(datetime_from[1].equalsIgnoreCase(months[i]))
                {
                    if(i<=9)
                    datetm_from=datetime_from[5]+"-"+"0"+Integer.toString(i)+"-"+datetime_from[2];
                    else
                    datetm_from=datetime_from[5]+"-"+Integer.toString(i)+"-"+datetime_from[2];

                }
                if(datetime_to[1].equalsIgnoreCase(months[i]))
                {
                    if(i<=9)
                    datetm_to=datetime_to[5]+"-"+"0"+Integer.toString(i)+"-"+datetime_to[2];
                    else
                    datetm_to=datetime_to[5]+"-"+Integer.toString(i)+"-"+datetime_to[2];

                }
            }
            System.out.println(" "+datetm_from);
            System.out.println(" "+datetm_to );

            System.out.println(dateFromDateChooser);
            String sql9="select AmtTxn,DtTmLcTxn from Dynamic_tb where DATE(dttmlctxn) <= '"+datetm_from+ "' and DATE(dttmlctxn) >= '"+datetm_to +"'";
            //String sql10="Select AmtTxn from Dynamic_tb where DtTmLcTxn=";
            System.out.println("query is"+sql9);
            ResultSet rs=stmt.executeQuery(sql9);
            while(rs.next())
            {
                System.out.println("enter the loop");
                String s=rs.getString(2);
                String dat[]=s.split(" ");
                long Amt=Long.parseLong(rs.getString(1));
             //   if(dat[0].equalsIgnoreCase(datetm_from))
             //   {

                   // System.out.println(dat[0]+" "+datetm);
                    sum = sum+Amt;

             //   }

            }
            System.out.println("Total amount is"+sum);
            /*      stmt.executeUpdate(sql3);
            stmt.executeUpdate(sql4);
            stmt.executeUpdate(sql5);
            stmt.executeUpdate(sql6);
            stmt.executeUpdate(sql7);
            stmt.executeUpdate(sql8);*/

            //  stmt.executeUpdate(sql11);
            //  System.out.println("deleted");
            // System.out.println("inserted");
            //String sql = "SELECT  AmtTxn FROM Dynamic_tb WHERE date = '" + click + "' ";
            //System.out.println(sql);
            //  stmt = con.createStatement();
            //stmt.executeQuery(sql);
            JOptionPane.showMessageDialog(this, "Amount"+ " "+sum);

        } 
        }catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      index = jComboBox1.getSelectedIndex();
      if(index==0)
      {
          jLabel3.setVisible(false);
          jComboBox2.setVisible(false);
          jComboBox3.setVisible(false);
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
         jDateChooser1.setVisible(true);
         jDateChooser2.setVisible(true);
          
      }
      else if (index==1)
      {
          jLabel3.setVisible(true);
          jComboBox2.setVisible(true);
          jComboBox3.setVisible(true);
          jLabel1.setVisible(false);
          jLabel2.setVisible(false);
          jDateChooser1.setVisible(false);
          jDateChooser2.setVisible(false);
      }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
//         int index = jComboBox1.getSelectedIndex();
//      if(index==1)
//          jPanel1.setVisible(false);
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new report().setVisible(true);
                
            }
            
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    

    

}
